force-app/main/default/objects/Appointment_Detail__c/Appointment_Detail__c.object-meta.xml
<CustomObject>
    <label>Appointment Detail</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Appointment Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AppointmentProject/force-app/main/default/objects/Appointment_Detail__c/fields/Appointment_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Time__c</fullName>
    <label>Appointment Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointment Details</relationshipLabel>
    <relationshipName>Appointment_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Slot__c/Appointment_Slot__c.object-meta.xml
<CustomObject>
    <label>Appointment Slot</label>
    <nameField>
        <displayFormat>AS-{0000000}</displayFormat>
        <label>Appointment Slot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AppointmentProject/force-app/main/default/objects/Appointment_Slot__c/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <label>Appointment Date</label>
    <type>Date</type>
</CustomField>

AppointmentProject/force-app/main/default/classes/AppointmentFormHandler.cls
public class AppointmentFormHandler {
    
    
    @AuraEnabled   //getAvailableTimeSlots method is used to check is there any available slot which is active based on the selected Appointment Date Time
    public static Boolean getAvailableTimeSlots(DateTime selectedDateTime){
        Boolean flag = false;
        try {           
            
            List<Appointment_Slot__c> bookedSlots = [SELECT Id, Appointment_Date__c, Start_Time__c, End_Time__c, isActive__c
                                                     FROM Appointment_Slot__c
                                                     WHERE Start_Time__c<=:selectedDateTime AND End_Time__c>=:selectedDateTime
                                                     AND isActive__c = true];
            if(!bookedSlots.isEmpty()){
                flag = true;
            }
        }
        catch (Exception e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        return flag;
    }
    
    
    @AuraEnabled  //createAppointment method is used to save an Appointment details on Appointment_Detail__c object
    public static void createAppointment(String subject, String description, String contactId, DateTime appointmentDateTime){
        try {
            Date appointmentDate = date.newinstance(appointmentDateTime.year(), appointmentDateTime.month(), appointmentDateTime.day());
            Appointment_Detail__c appointment = new Appointment_Detail__c();
            appointment.Subject__c = subject;
            appointment.Description__c = description;
            appointment.Contact__c = contactId;
            appointment.Appointment_Time__c = appointmentDateTime;
            appointment.Appointment_Date__c = appointmentDate;
            insert appointment;
        }
        catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        
    }
}